version: '3.7'

services:
  mysql:
    container_name: roles_control_mysql
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=adm_team_member
    security_opt:
      - seccomp:unconfined
    ports:
      - 3306:3306
    networks:
      - roles_control_network

networks:
  roles_control_network: